export const FETCH_QUESTIONS='FETCH_QUESTIONS' ;
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL='FETCH_QUESTIONS_FAIL';


export const UPDATE_RESPONSE = 'UPDATE_RESPONSE';
export const RESET_RESPONSE = 'RESET_RESPONSE';


export const UPDATE_SCORE= 'UPDATE_SCORE';
export const RESET_SCORE = 'RESET_SCORE';

export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const RESET_ANSWER= 'RESET_ANSWER';